export const numberKeys = [
  {
    id: 7,
    value: "7",
    title: "seven",
    keycode: 55,
    kbCode: "Digit7",
    type: "num",
  },
  {
    id: 8,
    value: "8",
    title: "eight",
    keycode: 56,
    kbCode: "Digit8",
    type: "num",
  },
  {
    id: 9,
    value: "9",
    title: "nine",
    keycode: 57,
    kbCode: "Digit9",
    type: "num",
  },
  {
    id: 4,
    value: "4",
    title: "four",
    keycode: 52,
    kbCode: "Digit4",
    type: "num",
  },
  {
    id: 5,
    value: "5",
    title: "five",
    keycode: 53,
    kbCode: "Digit5",
    type: "num",
  },
  {
    id: 6,
    value: "6",
    title: "six",
    keycode: 54,
    kbCode: "Digit6",
    type: "num",
  },
  {
    id: 1,
    value: "1",
    title: "one",
    keycode: 49,
    kbCode: "Digit1",
    type: "num",
  },
  {
    id: 2,
    value: "2",
    title: "two",
    keycode: 50,
    kbCode: "Digit2",
    type: "num",
  },
  {
    id: 3,
    value: "3",
    title: "three",
    keycode: 51,
    kbCode: "Digit3",
    type: "num",
  },  {
    id: 10,
    value: ".",
    title: "dot",
    keycode: 190,
    kbCode: "Period",
    type: "num",
  },
  {
    id: 0,
    value: "0",
    title: "zero",
      keycode: 48,
      kbCode: "Digit0",
      type: "num",
    },

  {
    id: 11,
    value: "m",
    uniChar: "\u00B1",
    title: "plus minus (m)",
    keycode: 189,
    kbCode: "KeyM",
    type: "num",
  },
];

export const functionKeys = [
  {
    id: 19,
    value: "+",
    title: "plus",
    keycode: 187,
    kbCode: "Equal",
    type: "func",
  },
  {
    id: 12,
    value: "-",
    title: "minus",
    keycode: 189,
    kbCode: "Minus",
    type: "func",
  },
  {
    id: 13,
    value: "x",
    uniChar: "\u00D7",
    title: "multiply (x)",
    keycode: 88,
    kbCode: "KeyX",
    type: "func",
  },
  {
    id: 14,
    value: "/",
    uniChar: "\u00F7",
    calculationDisplayChar: "\u00F7",
    title: "divide (/)",
    keycode: 191,
    kbCode: "Slash",
    type: "func",
  },
  {
    id: 15,
    value: "s",
    uniChar: "\uD835\uDC65\u00B2",
    calculationDisplayChar: "\u00B2",
    title: "square (s)",
    keycode: 83,
    kbCode: "KeyS",
    type: "func",
  },
  {
    id: 21,
    value: "r",
    uniChar: "\u00B2\u221A",
    calculationDisplayChar: "\u221A",
    title: "square root (r)",
    keycode: 82,
    kbCode: "KeyR",
    type: "func",
    ctrlKey: false,
  },
  {
    id: 20,
    value: "y",
    uniChar: "\uD835\uDC65\u02B8",
    title: "x to the power y (y)",
    keycode: 89,
    kbCode: "KeyY",
    type: "func",
  },
  {
    id: 16,
    value: "=",
    specialClass: "btn-success",
    title: "equals",
    keycode: 187,
    kbCode: "Equal",
    type: "func",
  },
];
export const utilityKeys = [
  {
    id: 17,
    value: "c",
    specialClass: "btn-danger",
    title: "clear last keypress (c)",
    keycode: 67,
    kbCode: "KeyC",
    type: "func",
  },
  {
    id: 18,
    value: "a",
    uniChar: "\u0061\u0063",
    specialClass: "btn-danger",
    title: "all clear (a)",
    keycode: 65,
    kbCode: "KeyA",
    type: "func",
  },
];

// allowed key codes for keyPress event handler
export const allowedKeys = [
  13, 16, 17, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 65, 67, 77, 82, 83,
  88, 89, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 109,
  110, 111, 187, 189, 190, 191,
];