import * as Types from "../types/types";
// allowed key codes for keyPress event handler
export const ALLOWED_KEYS: number[] = [
    8, 13, 16, 17, 27, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 67, 77, 82, 83,
    88, 89, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 109,
    110, 111, 187, 189, 190, 191,
];

export const DISALLOWED_KEYS: number[] = [
    9, 16, 17, 18, 37, 38, 39, 40, 91, 93,
];

const numberKeys: Types.TKey[] = [
    {
        id: "1",
        value: "1",
        title: "one",
        keycode: 49,
        code: "Digit1",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "2",
        value: "2",
        title: "two",
        keycode: 50,
        code: "Digit2",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "3",
        value: "3",
        title: "three",
        keycode: 51,
        code: "Digit3",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "4",
        value: "4",
        title: "four",
        keycode: 52,
        code: "Digit4",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "5",
        value: "5",
        title: "five",
        keycode: 53,
        code: "Digit5",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "6",
        value: "6",
        title: "six",
        keycode: 54,
        code: "Digit6",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "7",
        value: "7",
        title: "seven",
        keycode: 55,
        code: "Digit7",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "8",
        value: "8",
        title: "eight",
        keycode: 56,
        code: "Digit8",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "9",
        value: "9",
        title: "nine",
        keycode: 57,
        code: "Digit9",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "0",
        value: "0",
        title: "zero",
        keycode: 48,
        code: "Digit0",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "10",
        value: ".",
        title: "dot",
        keycode: 190,
        code: "Period",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
    },
    {
        id: "11",
        value: "m",
        // uniChar: "\u00B1",
        uniChar: "\u207A\u2044-",
        title: "plus minus (m)",
        keycode: 77,
        code: "KeyM",
        type: "number",
        location: "main",
        className: "btn btn-lg btn-primary",
        subTitle: "m",
    },
];

const functionKeys: Types.TKey[] = [
    {
        id: "19",
        value: "+",
        title: "plus",
        keycode: 187,
        code: "Equal",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
    },
    {
        id: "12",
        value: "-",
        title: "minus",
        keycode: 189,
        code: "Minus",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
    },
    {
        id: "13",
        value: "x",
        title: "multiply (x)",
        keycode: 88,
        code: "KeyX",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
        uniChar: "\u00D7",
        calculationDisplayChar: "\u00D7",
        subTitle: "x",
    },
    {
        id: "14",
        value: "/",
        title: "divide (/)",
        keycode: 191,
        code: "Slash",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
        uniChar: "\u00F7",
        calculationDisplayChar: "\u00F7",
        subTitle: "/",
    },
    {
        id: "15",
        value: "s",
        title: "square (s)",
        keycode: 83,
        code: "KeyS",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
        uniChar: "\uD835\uDC65\u00B2",
        calculationDisplayChar: "\u00B2",
        subTitle: "s",
    },
    {
        id: "21",
        value: "r",
        title: "square root (r)",
        keycode: 82,
        code: "KeyR",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
        uniChar: "\u221A2",
        calculationDisplayChar: "\u221A",
        subTitle: "r",
        ctrlKey: false,
    },
    {
        id: "20",
        value: "y",
        title: "x to the power y (y)",
        keycode: 89,
        code: "KeyY",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-secondary",
        uniChar: "\uD835\uDC65\u02B8",
        calculationDisplayChar: "\u02B8",
        subTitle: "y",
    },
    {
        id: "16",
        value: "=",
        title: "equals",
        keycode: 187,
        code: "Equal",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-success btn-secondary",
    },
    {
        id: "17",
        value: "c",
        title: "clear last keypress (backspace)",
        keycode: 8,
        code: "Backspace",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-danger btn-secondary",
        subTitle: "\u232b", // erase left
        // subTitle: "\u2190", // left arrow
        // subTitle: "\u27A9", // left arrow 3d
        // subTitle: "bksp",
    },
    {
        id: "18",
        value: "a",
        title: "all clear (esc)",
        keycode: 27,
        code: "Escape",
        type: "function",
        location: "main",
        className: "btn btn-lg btn-danger btn-secondary",
        uniChar: "\u0061\u0063",
        subTitle: "esc",
    },
];

const themeTypeKeys: Types.TKey[] = [
    {
        id: "picture",
        value: "picture",
        title: "picture",
        keycode: 65,
        code: "KeyA",
        type: "themeType",
        location: "display",
        className: "btn btn-lg btn-theme-type",
        uniChar: "\uD83D\uDCF8",
        showTitle: true,
    },
    {
        id: "color",
        value: "color",
        title: "color",
        keycode: 65,
        code: "KeyA",
        type: "themeType",
        location: "display",
        className: "btn btn-lg btn-theme-type",
        uniChar: "\uD83C\uDFA8",
        showTitle: true,
    },
    {
        id: "animation",
        value: "animation",
        title: "animation",
        keycode: 65,
        code: "KeyA",
        type: "themeType",
        location: "display",
        className: "btn btn-lg move-it btn-theme-type",
        uniChar: "\uD83D\uDE80",
        showTitle: true,
        // uniChar: "\u221E",
    },
];

const themeKeys: Types.TKey[] = [
    {
        id: "fire",
        value: "fire",
        title: "fire",
        keycode: 55,
        code: "Digit7",
        type: "theme",
        location: "display",
        className: "btn btn-lg btn-fire fire btn-theme",
        uniChar: "\uD83D\uDD25",
        showTitle: true,
    },
    {
        id: "midnight",
        value: "midnight",
        title: "midnight",
        keycode: 55,
        code: "Digit7",
        type: "theme",
        location: "display",
        className: "btn btn-lg btn-midnight midnight btn-theme",
        uniChar: "\uD83C\uDF03",
        showTitle: true,
    },
    {
        id: "ocean",
        value: "ocean",
        title: "ocean",
        keycode: 55,
        code: "Digit7",
        type: "theme",
        location: "display",
        className: "btn btn-lg btn-ocean ocean btn-theme",
        uniChar: "\uD83C\uDF0A",
        showTitle: true,
    },
    {
        id: "storm",
        value: "storm",
        title: "storm",
        keycode: 55,
        code: "Digit7",
        type: "theme",
        location: "display",
        className: "btn btn-lg btn-storm storm btn-theme",
        uniChar: "\u2614",
        showTitle: true,
    },
    {
        id: "jungle",
        value: "jungle",
        title: "jungle",
        keycode: 55,
        code: "Digit7",
        type: "theme",
        location: "display",
        className: "btn btn-lg btn-jungle jungle btn-theme",
        uniChar: "\uD83C\uDF33",
        showTitle: true,
    },
];

const animationKeys: Types.TKey[] = [
    {
        id: "slither",
        value: "slither",
        title: "slither",
        keycode: null,
        code: "",
        type: "animation",
        location: "display",
        uniChar: "\u219D",
        className: "btn btn-lg btn-animation-choose",
        showTitle: true,
        // uniChar: "\uD83D\uDD00",
    },
    {
        id: "fireworks",
        value: "fireworks",
        title: "fireworks",
        keycode: null,
        code: "",
        type: "animation",
        location: "display",
        className: "btn btn-lg btn-animation-choose",
        uniChar: "\uD83D\uDCA5", // explosion
        showTitle: true,
        // uniChar: "\uD83C\uDF87",// sparkler
        // uniChar: "\uD83C\uDF86",// firework
    },
    // {
    //     id: "twist",
    //     value: "twist",
    //     // uniChar: "\uD83D\uDD00",// twisted-right
    //     // uniChar: "\uD83D\uDD01",// Clockwise Rightwards and Leftwards Open Circle Arrows
    //     // uniChar: "\uD83C\uDF0C" ,// milkyway symbol
    //     uniChar: "\uD83D\uDCAB", // dizzy symbol
    //     title: "twist",
    //     keycode: null,
    //     code: "",
    //     type: "animation",
    //     location: "display",
    // className: "btn btn-lg btn-animation-choose",
    //     showTitle: true,
    // },
];

// 0xD83C 0xDFAE ps4 controller
// 0xD83D 0xDCA3 bomb
// 0xD83D 0xDD2B pistol

const pictureKeys: Types.TKey[] = [
    {
        id: "still",
        value: "still",
        title: "still",
        keycode: 55,
        code: "Digit7",
        type: "pictureType",
        location: "display",
        className: "btn btn-lg btn-still still btn-pic-type",
        uniChar: "\uD83D\uDDBC",
        showTitle: true,
    },
    {
        id: "moving",
        value: "moving",
        title: "motion",
        keycode: 55,
        code: "Digit7",
        type: "pictureType",
        location: "display",
        className: "btn btn-lg btn-moving moving btn-pic-type",
        uniChar: "\uD83D\uDCF9",
        showTitle: true,
    },
];

export const keyboardKeysMap = new Map<string, Types.TKey[]>([
    ["number", numberKeys],
    ["function", functionKeys],
    ["themeType", themeTypeKeys],
    ["theme", themeKeys],
    ["animation", animationKeys],
    ["pictureType", pictureKeys],
]);

export const keyMap = new Map<string, Types.TKey>([
    ["1", numberKeys[0]],
    ["2", numberKeys[1]],
    ["3", numberKeys[2]],
    ["4", numberKeys[3]],
    ["5", numberKeys[4]],
    ["6", numberKeys[5]],
    ["7", numberKeys[6]],
    ["8", numberKeys[7]],
    ["9", numberKeys[8]],
    ["0", numberKeys[9]],
    ["10", numberKeys[10]],
    ["11", numberKeys[11]],
    ["19", functionKeys[0]],
    ["12", functionKeys[1]],
    ["13", functionKeys[2]],
    ["14", functionKeys[3]],
    ["15", functionKeys[4]],
    ["21", functionKeys[5]],
    ["20", functionKeys[6]],
    ["16", functionKeys[7]],
    ["17", functionKeys[8]],
    ["18", functionKeys[9]],
    ["picture", themeTypeKeys[0]],
    ["color", themeTypeKeys[1]],
    ["animation", themeTypeKeys[2]],
    ["fire", themeKeys[0]],
    ["midnight", themeKeys[1]],
    ["ocean", themeKeys[2]],
    ["storm", themeKeys[3]],
    ["jungle", themeKeys[4]],
    ["slither", animationKeys[0]],
    ["fireworks", animationKeys[1]],
    ["still", pictureKeys[0]],
    ["moving", pictureKeys[1]],
]);
